Snhut 2705 groupuserlist
snhuproduct/turbine pull request #134
Opened 2022-12-28 08:18 UTC by lekshmic-sadaindia

### Description

- API Integration ticket for listing users of a group

#### Screenshots
<img width="1728" alt="Screen Shot 2022-12-28 at 1 45 14 PM" src="https://user-images.githubusercontent.com/118151666/209780882-bba934cf-f029-41e7-adb9-c952056e783c.png">

### Other Details

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2705)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

### Pending Task
Data returning from api is not accurate, hence testing is blocked

2022-12-28 08:21 UTC, lekshmic-sadaindia commented
Moving to draft since dev testing is still pending and have dependency on gp-core.

2023-01-25 16:00 UTC, shafi-sadaindia approved these changes
LGTM

2023-02-02 13:16 UTC, sada-ajith requested changes
PLease check my comments

2023-02-02 13:16 UTC, sada-ajith commented on apps/toboggan-api/src/app/modules/groups/groups.service.ts
> +    return this.httpService.put(`/group/${uuid}`, user_ids);
are we passing user_ids for updating group. ?

2023-02-02 13:16 UTC, sada-ajith commented on apps/toboggan-app/src/app/group/components/add-users/add-users.component.spec.ts
> +    const approveGroupSpy = jest.spyOn(groupService, 'addUsersToGroup');
shouldn't it be calling updateGroup ?

2023-02-02 13:16 UTC, sada-ajith commented on apps/toboggan-app/src/app/group/components/list-users/list-users.component.ts
> +  id: any;
Please rename variable according to context

2023-02-02 13:35 UTC, lekshmic-sadaindia commented on apps/toboggan-api/src/app/modules/groups/groups.service.ts
> +    return this.httpService.put(`/group/${uuid}`, user_ids);
Good catch!

2023-02-02 13:35 UTC, lekshmic-sadaindia commented on apps/toboggan-app/src/app/group/components/add-users/add-users.component.spec.ts
> +    const approveGroupSpy = jest.spyOn(groupService, 'addUsersToGroup');
No that logic is changed. we've new api endpoints to add and remove users from group

    component:      await this.groupService.**addUsersToGroup**(body, this.group.uuid);
[https://snhu-glidepath-dev-api.cloudpssolutions.com/docs/user-management/api/v1/redoc#tag/Group/operation/add_user_to_group_group__uuid__add_users_post](    https://snhu-glidepath-dev-api.cloudpssolutions.com/docs/user-management/api/v1/redoc#tag/Group/operation/add_user_to_group_group__uuid__add_users_post)

2023-02-09 07:47 UTC, shafi-sadaindia approved these changes
LGTM

2023-02-10 10:03 UTC, lekshmic-sadaindia commented
> PLease check my comments

Addressed review comments

2023-02-10 10:06 UTC, lekshmic-sadaindia commented on apps/toboggan-app/src/app/group/components/list-users/list-users.component.ts
> +  id: any;
Variable renamed.

2023-02-10 10:32 UTC, sada-ajith approved these changes

2023-02-10 10:32 UTC, merged