Snhut 2258 Staff Profile UI implementaion with mock endpoints
snhuproduct/turbine pull request #135
Opened 2022-12-29 10:11 UTC by Mubashir-sadaindia

### Description

- To create a new module/page for displaying and updating staff profiles (Personal and Contact details) with the help of mock endpoints (Which has to be updated when the endpoints are provided by the Backend team)

### Video 
[Sample Demo.webm](https://user-images.githubusercontent.com/118154040/209935774-540937a6-da59-4cd2-9b9e-d8b413e17cee.webm)

#### Screen shots
<img width="2056" alt="Screen Shot 2022-12-29 at 3 35 31 PM" src="https://user-images.githubusercontent.com/118154040/209936052-7ecad4fa-026f-495b-97a5-90aaf4f6f768.png">
<img width="2056" alt="Screen Shot 2022-12-29 at 3 35 40 PM" src="https://user-images.githubusercontent.com/118154040/209936062-f55c463f-635b-41fd-87de-c76c83587954.png">

### Other Details

- Sample id `uuid:1234567890`, if needed to navigate and test it out 

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2258)
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2259)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2022-12-30 04:58 UTC, sada-ajith requested changes
Could you please work in requested changes

2022-12-30 04:58 UTC, sada-ajith commented on apps/toboggan-api/src/staff-profile/staff-profile.service.ts
> +			this.staffProfile = {
move this to a mock file which can reused in unit testing context as well

2022-12-30 04:58 UTC, sada-ajith commented on apps/toboggan-app/src/app/staff-profile/services/staff-profile.service.spec.ts
> +    expect(service).toBeTruthy();
add unit tests

2022-12-30 04:58 UTC, sada-ajith commented on apps/toboggan-api/src/staff-profile/staff-profile.controller.spec.ts
> +    expect(controller).toBeDefined();
Please add unit tests

2023-01-02 15:08 UTC, sada-ajith requested changes
Please check my notes

2023-01-02 15:08 UTC, sada-ajith commented on apps/toboggan-api/src/staff-profile/staff-profile.service.spec.ts
> +  it('should be defined', () => {
add unit tests for service as well

2023-01-02 15:08 UTC, sada-ajith commented on apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.scss
> +    // padding: 32px;
could you please remove this comment?

2023-01-02 15:08 UTC, sada-ajith commented on apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.ts
> +    phoneNumber: 'If you don’t want learners to have your personal phone number, you can generate a new number using a free online masking service and enter that here. Incoming calls or texts will st
Please add necessary unit tests for this component

2023-01-02 15:08 UTC, sada-ajith commented on apps/toboggan-app/src/app/staff-profile/components/personal-tab/personal-tab.component.ts
> +    });
Please add necessary unit tests for this component

2023-01-02 15:08 UTC, sada-ajith commented on apps/toboggan-app/src/app/staff-profile/pages/staff-profile-main-page/staff-profile-main-page.component.ts
> +
Please add necessary unit tests for this component

2023-01-03 06:30 UTC, Mubashir-sadaindia commented on apps/toboggan-api/src/staff-profile/staff-profile.service.ts
> +			this.staffProfile = {
done

2023-01-03 06:40 UTC, Mubashir-sadaindia commented on apps/toboggan-app/src/app/staff-profile/services/staff-profile.service.spec.ts
> +    expect(service).toBeTruthy();
done

2023-01-03 06:40 UTC, Mubashir-sadaindia commented on apps/toboggan-api/src/staff-profile/staff-profile.service.spec.ts
> +  it('should be defined', () => {
done

2023-01-03 06:40 UTC, Mubashir-sadaindia commented on apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.scss
> +    // padding: 32px;
done

2023-01-03 06:40 UTC, Mubashir-sadaindia commented on apps/toboggan-app/src/app/staff-profile/components/personal-tab/personal-tab.component.ts
> +    });
done

2023-01-03 08:03 UTC, Mubashir-sadaindia commented on apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.ts
> +    phoneNumber: 'If you don’t want learners to have your personal phone number, you can generate a new number using a free online masking service and enter that here. Incoming calls or texts will st
done

2023-01-03 10:23 UTC, sada-ajith approved these changes

2023-01-03 10:27 UTC, merged