Snhut 3113 assessment list
snhuproduct/turbine pull request #138
Opened 2023-01-10 09:11 UTC by lekshmic-sadaindia

### Description

As an assessor, I need the ability to find assessments assigned to me, see all current open Assessments and find the link to previously Evaluated Assessments.

#### Screenshots

<img width="1263" alt="Screen Shot 2023-01-10 at 12 42 54 PM" src="https://user-images.githubusercontent.com/118151666/211485348-1d6d851b-a9be-48b9-84ef-5e4c23d4c939.png">

<img width="1263" alt="Screen Shot 2023-01-10 at 12 42 47 PM" src="https://user-images.githubusercontent.com/118151666/211485330-8c7fa6aa-b368-40cd-91a1-5de66f252cf7.png">

<img width="1263" alt="Screen Shot 2023-01-10 at 12 47 01 PM" src="https://user-images.githubusercontent.com/118151666/211486610-54b2b285-42a4-4401-bde8-bd52dd703478.png">

### JIRA

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-3184)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2023-01-10 09:28 UTC, shafi-sadaindia approved these changes
LGTM

2023-01-10 13:14 UTC, sada-ajith requested changes

2023-01-10 13:14 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluated-list/assessment-evaluated-list.component.spec.ts
>  import { NoopAnimationsModule } from '@angular/platform-browser/animations';
Please correct naming for these components as , this component is evaluation backlog rather than evaluated list

2023-01-10 13:14 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluated-list/assessment-evaluated-list.component.ts
> +      case action.startsWith('Evaluate for') ? action : '':
can we move it outside switch ?

2023-01-12 16:03 UTC, sada-ajith requested changes
Could you please check into my comments ?

2023-01-12 16:03 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluation-backlog/assessment-evaluation-backlog.component.spec.ts
> +import { AssessmentEvaluationBacklogComponent } from './assessment-evaluation-backlog.component';
I believe we are already in assessment context , 
AssessmentEvaluationBacklogComponent -> can be EvaluationBacklogComponent ?

2023-01-12 16:03 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluation-backlog/assessment-evaluation-backlog.component.spec.ts
> +  const mockEvaluationBacklogAssessmentService = {
please name mocks according to context -> here service is assessmentService ? not evaluationBacklogService ?

2023-01-12 16:03 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluation-backlog/assessment-evaluation-backlog.component.ts
> +      const timeLeftCellColor =
can we refactor this as a function and call it here ?

2023-01-12 16:03 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluation-backlog/assessment-evaluation-backlog.component.ts
> +        this.assessmentService.fetchEvaluationBacklogAssessments(),
fetchEvaluationBacklog is kind of enough :-) ?

2023-01-16 10:39 UTC, sada-ajith requested changes
Please address review comments I have noted down

2023-01-16 14:04 UTC, sada-ajith approved these changes

2023-01-16 14:13 UTC, merged