Assessment grading view
snhuproduct/turbine pull request #168
Opened 2023-02-07 12:35 UTC by pran-sada

### Description

- Submitted assessment details view with rubrics and multiple attempts

#### Video

https://user-images.githubusercontent.com/116863369/217245933-b4b0b419-fd97-4101-bbc7-77ef9cf9eb05.mp4

### Other Details

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2184)
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2185)
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2186)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2023-02-08 10:20 UTC, sada-ajith requested changes

2023-02-08 10:20 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/interface/assessments.type.ts
> +export enum RuleEngineVerb {
keep items commonly used for rule engine for api and UI in toboggan-common

2023-02-09 07:41 UTC, shafi-sadaindia commented on apps/toboggan-api/src/app/modules/assessments/assessments.service.ts
> +      `/submitted-assessments?assessor_id=${assessor_id}&status=${status}`
Just a suggestion: shall we generate url params from object?.
ex : getAssessmentsById({assessor_id: id, status:'status'});

2023-02-09 09:44 UTC, pran-sada commented on apps/toboggan-api/src/app/modules/assessments/assessments.controller.ts
> +  @Post('/learnosity/init/assessment') //! Temporary endpoint
Removed

2023-02-09 09:45 UTC, pran-sada commented on apps/toboggan-api/src/app/app.module.ts
> +    TypeOrmModule.forRoot({
Removed the unwanted modules

2023-02-09 09:45 UTC, pran-sada commented on apps/toboggan-api/src/app/app.module.ts
> +    LearnosityModule,
Removed unwanted modules

2023-02-09 09:45 UTC, pran-sada commented on apps/toboggan-api/src/app/modules/rule-engine/rule-engine.dto.ts
> +import { RuleEngineNodeType, RuleEngineVerb } from './rule-engine.types';
Renaming done

2023-02-09 09:46 UTC, pran-sada commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +          // instructor: cellData.instructor,
Removed the commented code

2023-02-09 09:46 UTC, pran-sada commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-table.type.ts
> -export enum RowActions {
This was moved to another file where we stored the enum values

2023-02-09 09:47 UTC, pran-sada commented on apps/toboggan-app/src/app/assessment/components/assessment-submission-details/assessment-submission-details.component.ts
> +    if (attemptNo <= 1) return;
Made it to a common function

2023-02-09 09:48 UTC, pran-sada commented on apps/toboggan-app/src/app/assessment/interface/assessments.type.ts
> +export enum RuleEngineVerb {
Nest use snake case and Angular uses camel case, hence the key values will be different

2023-02-09 09:50 UTC, pran-sada commented on apps/toboggan-api/src/app/modules/assessments/assessments.service.ts
> +      `/submitted-assessments?assessor_id=${assessor_id}&status=${status}`
These are query params not passed with body

2023-02-09 10:42 UTC, shafi-sadaindia commented on apps/toboggan-api/src/app/modules/assessments/assessments.service.ts
> +      `/submitted-assessments?assessor_id=${assessor_id}&status=${status}`
Nop. we can add more params by converting an object to query params.

2023-02-09 11:31 UTC, sada-ajith approved these changes

2023-02-09 11:42 UTC, merged