SNHUT 2644:  Permissions api integration
snhuproduct/turbine pull request #193
Opened 2023-02-22 10:55 UTC by hilal-sadaindia

### Description

- SNHUT 2644:  Permissions api integration

### Video or Screenshots

#### Video

- Paste your link here.

#### Screenshots

<img width="1728" alt="Screenshot 2023-02-22 at 4 08 29 PM" src="https://user-images.githubusercontent.com/111114994/220599777-fad8fa6a-d281-43ca-a0e8-f778f70e76df.png">

### Other Details

- [SNHUT-2644](https://collectiveshift.atlassian.net/browse/SNHUT-2644)

#### Checklist

- [x] **Assumptions of User Story met (including acceptance criteria)**
- [x] **All new necessary Unit tests were CREATED** to promote code coverage
- [x] **All required unit tests are PASSING**
- [x] The proposed functionality was tested manually locally, and it's working fine.
- [x] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [x] Unnecessary console.logs AND/OR comments were removed
- [x] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [x] Ensure configuration and/or build changes documented

2023-02-22 12:02 UTC, sada-ajith requested changes
Please see changes

2023-02-22 12:02 UTC, sada-ajith commented on apps/toboggan-app/src/app/permission/services/permission.service.ts
> +    return this.http.get<IPermission[]>('/api/permissions?skip=0&limit=100&fetch_tree=true');
default value should be handled in nestjs

2023-02-22 12:02 UTC, sada-ajith commented on libs/toboggan-common/src/lib/toboggan-common.ts
> +export interface IIPermission {
Why is it named as `IIPermission` rather than `IPermission`

2023-02-22 12:02 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/services/assessment.service.ts
> +  fetchAssessments() {
why do we have assessment-related API end points added to this PR? 

Please verify with @pran-sada

2023-02-22 12:09 UTC, sada-ajith requested changes

2023-02-22 12:09 UTC, sada-ajith commented on apps/toboggan-app/src/app/permission/components/permissions-list/permissions-list.component.ts
> +  private sortPermissions(permissions: IIPermission[]) {
this logic won't work

2023-02-23 10:13 UTC, hilal-sadaindia commented on apps/toboggan-api/src/app/modules/permissions/permissions.service.ts
> +  deletePermission(uuid: string) {
removed

2023-02-23 10:13 UTC, hilal-sadaindia commented on apps/toboggan-api/src/app/modules/permissions/permissions.service.ts
> +  updatePermission(uuid: string, updatedPermission: IPermission) {
removed

2023-02-28 12:14 UTC, sada-ajith approved these changes

2023-02-28 12:14 UTC, merged