NS - User Mgmt - Staff Landing Pages
snhuproduct/turbine pull request #194
Opened 2023-02-22 15:16 UTC by shafi-sadaindia

### Description

- NS - User Mgmt - Staff Landing Pages

#### Screenshots

<img width="1728" alt="Screenshot 2023-02-22 at 8 43 45 PM" src="https://user-images.githubusercontent.com/102204577/220666182-cbe655a9-d894-4344-af90-1371deb5dce1.png">

### Other Details

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-3503)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2023-02-24 09:45 UTC, sada-ajith requested changes

2023-02-24 09:45 UTC, sada-ajith commented on apps/toboggan-app/src/app/landing/components/landing/landing.component.spec.ts
> +  it('should create', () => {
Can you add few more test cases ?

2023-02-24 09:45 UTC, sada-ajith commented on apps/toboggan-app/src/app/landing/components/landing/landing.component.ts
> +    const currentUser = this.authService.getUserId();
can we move this to auth service so , that if we need it in usertype somwhere else , we can reuse it ?  ( may be store it in localstorage )

2023-02-24 09:45 UTC, sada-ajith commented on apps/toboggan-app/src/app/landing/pages/landing-main-page/landing-main-page.component.ts
> +  // eslint-disable-next-line @typescript-eslint/no-empty-function
we can remove this constructor

2023-02-24 13:32 UTC, shafi-sadaindia commented on apps/toboggan-app/src/app/landing/components/landing/landing.component.ts
> +    const currentUser = this.authService.getUserId();
I have added getUserId method in authservice. it is calling from authservice itself.

2023-02-24 13:33 UTC, shafi-sadaindia commented on apps/toboggan-app/src/app/landing/components/landing/landing.component.spec.ts
> +  it('should create', () => {
Done

2023-02-24 13:34 UTC, shafi-sadaindia commented on apps/toboggan-app/src/app/landing/pages/landing-main-page/landing-main-page.component.ts
> +  // eslint-disable-next-line @typescript-eslint/no-empty-function
Done

2023-02-27 16:12 UTC, sada-ajith requested changes

2023-02-27 16:12 UTC, sada-ajith commented on apps/toboggan-app/src/app/shared/auth/auth.service.ts
> +          const userDetails: any = await firstValueFrom(this.userService.getUser(userSession.userId));
this should part of sign in credentials as well

2023-02-27 16:12 UTC, sada-ajith commented on apps/toboggan-app/src/app/shared/auth/auth.service.ts
> +  getUserDetails() {
we already have a function for current user
Please refer
https://github.com/snhuproduct/turbine/blob/d02ddea65652c6fcfc9a40e152866a69398de3a8/apps/toboggan-app/src/app/shared/auth/auth.service.ts#L238

2023-02-27 16:12 UTC, sada-ajith commented on apps/toboggan-app/src/app/shared/services/user/user.service.ts
> +  getUser(id : string) {
can we replace id with uuid. ?

2023-02-28 11:49 UTC, sada-ajith approved these changes

2023-03-02 14:51 UTC, merged