Snhut 4926 auth bugfix
snhuproduct/turbine pull request #392
Opened 2023-04-03 14:25 UTC by shafi-sadaindia

### Description
If the signed-out user hits URL: /turbine-admin, the Application will redirect to the same URL after login.

- Fixed redirect URL Globally.

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-4305)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2023-04-03 19:45 UTC, mk-sada requested changes
This works, but two issues.
1. You've linked [SNHUT-4305](https://collectiveshift.atlassian.net/browse/SNHUT-4305) to this item, but I'm struggling to see the relationship between what you did and what the ticket is asking you to solve.
2. This touches the `auth.guard.ts`, which is a rather crucial component, and I'd rather not make any change to it before alpha release for a PLA item.

---

If you can help me understand why this change is necessary, we can revisit this and merge it after April 6th.

2023-04-04 06:42 UTC, shafi-sadaindia commented
> This works, but two issues.
> 
> 1. You've linked [SNHUT-4305](https://collectiveshift.atlassian.net/browse/SNHUT-4305) to this item, but I'm struggling to see the relationship between what you did and what the ticket is asking you to solve.
> 2. This touches the `auth.guard.ts`, which is a rather crucial component, and I'd rather not make any change to it before alpha release for a PLA item.
> 
> If you can help me understand why this change is necessary, we can revisit this and merge it after April 6th.

2023-04-04 06:44 UTC, shafi-sadaindia commented
> This works, but two issues.
> 
> 1. You've linked [SNHUT-4305](https://collectiveshift.atlassian.net/browse/SNHUT-4305) to this item, but I'm struggling to see the relationship between what you did and what the ticket is asking you to solve.
> 2. This touches the `auth.guard.ts`, which is a rather crucial component, and I'd rather not make any change to it before alpha release for a PLA item.
> 
> If you can help me understand why this change is necessary, we can revisit this and merge it after April 6th.

Hi @mk-sada ,

Added wrong ticket by mistake. Actual ticket is https://collectiveshift.atlassian.net/browse/SNHUT-4926. Updated discription

2023-04-06 14:06 UTC, mk-sada commented
I verified that the code works, and it does address the bug.
Now that we are not in a crunch, I would like us to clean up the auth/reroute logic some more.
Would you mind addressing my inline comments in `auth.service.ts`?

2023-04-06 14:09 UTC, mk-sada commented on microservices/turbine-admin/apps/toboggan-app/src/app/shared/auth/auth.service.ts
> +      if (url === '/' || url === '') {
Let's handle the logic for each non-learner user using switch-case statements instead of nested if-else.
Non-learner users being:
- Admin [test_admin.006@leveluplabs.org]
- assessor [test_assessor.006@leveluplabs.org]
- coach [test_coach.006@leveluplabs.org]
- instructor [test_instructor.006@leveluplabs.org]
- LXE [test_LXE.004@leveluplabs.org]

2023-04-06 14:11 UTC, mk-sada commented on microservices/turbine-admin/apps/toboggan-app/src/app/shared/auth/auth.service.ts
> +          this.router.navigate(['/content-management'], {
make sure to `await` the `router.navigate` calls. E.g.:

```TypeScript
await this.router.navigate(['/content-management'], {
```

2023-04-06 18:43 UTC, mk-sada approved these changes

2023-04-06 18:43 UTC, merged