SNHUT - 4537 - 4300 - 4780
snhuproduct/turbine pull request #406
Opened 2023-04-05 09:48 UTC by grace-sadaindia

### Description

- This pull request is combined for three tickets. Ticket 4537 (Click on the Title of the card to see the Modal pop up displaying additional details), Ticket 4300 (End of Search Results Screen - Frontend) which is the last card that is displayed at the end of the search results from prior experience search and has two functional buttons, and Ticket 4780 (Sessions - Card Views - frontend) which is the saved tab in prior experience page currently displaying the cards based on dummy data and functionality to toggle between the two card views.

### Video or Screenshots

#### Video

https://user-images.githubusercontent.com/109648439/230045224-da79536d-d36c-49de-923c-24466e7c4fac.mp4

#### Screenshots
<img width="1728" alt="Screenshot 2023-04-10 at 5 35 47 PM" src="https://user-images.githubusercontent.com/109648439/230900688-73c8e188-dc17-4c42-bad3-995705cd8fd2.png">
<img width="1840" alt="Screenshot 2023-04-05 at 1 27 43 PM" src="https://user-images.githubusercontent.com/109648439/230026179-ad8d6d58-aff3-4def-ad32-da2c74cc0294.png">
<img width="1840" alt="Screenshot 2023-04-05 at 1 27 53 PM" src="https://user-images.githubusercontent.com/109648439/230026652-c3fe817d-52f4-454b-b923-45ecc66bbe98.png">
<img width="1840" alt="Screenshot 2023-04-05 at 1 27 59 PM" src="https://user-images.githubusercontent.com/109648439/230026876-91ecca99-6edc-491f-8795-0db14b49bf96.png">

### Other Details

- [SNHUT-4537](https://collectiveshift.atlassian.net/browse/SNHUT-4537)
- [SNHUT-4300](https://collectiveshift.atlassian.net/browse/SNHUT-4300)
- [SNHUT-4780](https://collectiveshift.atlassian.net/browse/SNHUT-4780)

#### Checklist

- [x] **Assumptions of User Story met (including acceptance criteria)**
- [x] **All new necessary Unit tests were CREATED** to promote code coverage
- [x] **All required unit tests are PASSING**
- [x] The proposed functionality was tested manually locally, and it's working fine.
- [x] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [x] Unnecessary console.logs AND/OR comments were removed
- [x] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [x] Ensure configuration and/or build changes documented

[SNHUT-4537]: https://collectiveshift.atlassian.net/browse/SNHUT-4537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/stack-card/stack-card.component.ts
> +    this.courseDescription = this.card.description
Convert variable to an object and define a model (reusable). this.card is an object

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/stack-card/stack-card.component.spec.ts
> +    expect(component).toBeTruthy();
Please write test

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/stack-card/stack-card.component.html
> +<!-- <gp-card-catalog-information-card id="stackcard" actionType="button" [tags]="tags" actionType="button"
Remove comments

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.ts
> +    this.courseDescription = this.card.description;
Convert variable to an object and define a model (reusable). this.card is an object

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.spec.ts
> +  it('should create', () => {
Write test

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.ts
> +    // this.dataService.getData().subscribe((data) => {
Remove comments

2023-04-05 10:07 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.ts
> +    this.priorExperienceForm = fb.group({
change to FormGroup. Please refer add users component

2023-04-05 10:49 UTC, shafi-sadaindia requested changes

2023-04-05 10:49 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/pop-up/pop-up.component.html
> +<div class="courseDetails">
Class name should be kabab-case format

2023-04-05 12:07 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/pop-up/pop-up.component.ts
> +export class PopUpComponent implements AfterViewInit {
Renamed the PopUpComponent to ModalTitleComponent.
Issues:
1. The modal interior scrolling is not working.
2. The spec file for ModalTitleComponent is failing.

2023-04-10 05:22 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/pop-up/pop-up.component.ts
> +export class PopUpComponent implements AfterViewInit {
Nop. It should be title "Experience Details"

2023-04-10 05:35 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/pop-up/pop-up.component.ts
> +export class PopUpComponent implements AfterViewInit {
Removed the separate component for ModalTitleComponent, the usage of that modal is integrated in stackCard and smallCard components.

2023-04-10 06:41 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.spec.ts
> +      expect(cardData.description).toEqual('Test Description');
2 or 3 expect should be fine

2023-04-10 06:41 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.ts
> +  public mapApiToCardData(apiData: any) {
Define a interface instead of using any.

2023-04-10 06:42 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.html
> +                [description]="data.description"
Pass an object instead of passing different fields.

2023-04-10 06:48 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/search-bar/search-bar.component.html
> -          [id]="data['code']"
Pass an object instead of passing different fields.

2023-04-10 06:48 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/search-bar/search-bar.component.html
> -          [id]="data['code']"
Pass an object instead of passing different fields.

2023-04-10 06:48 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.html
> +[title]="smallCardData.courseTitle"
Pass an object instead of passing different fields.

2023-04-10 06:48 UTC, shafi-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.html
> +    <p><strong>Code</strong><br>{{card.code}}</p>
Render each line from an object/array

2023-04-10 08:46 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.html
> +    <p><strong>Code</strong><br>{{card.code}}</p>
Used a dictionary with built-in keyvalue pipe in angular.

2023-04-10 08:54 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/search-bar/search-bar.component.html
> -          [id]="data['code']"
removed these lines of code from search bar component.

2023-04-10 08:54 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/search-bar/search-bar.component.html
> -          [id]="data['code']"
removed these lines of code from search bar component.

2023-04-10 08:59 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.spec.ts
> +      expect(cardData.description).toEqual('Test Description');
remove extra expect statements.

2023-04-10 11:02 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.ts
> +  public mapApiToCardData(apiData: any) {
created ISavedSessions interface in toboggan-common and replaced any with the interface

2023-04-10 12:09 UTC, shafi-sadaindia approved these changes
LGTM

2023-04-11 08:55 UTC, sada-ajith requested changes
Could you please look into the comments I have noted ?

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.html
> +    <ng-container *ngIf="informationData?.length">
can't we use "savedSessions" as variable name rather than "informationData"
or this variable denotes something else ?

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.scss
> +    margin-bottom: 10px;
we can use "row-gap" property rather than margin to each element 
Its much cleaner
https://css-tricks.com/almanac/properties/r/row-gap/

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.spec.ts
> +  describe('viewLargeCard', () => {
If multiple scenarios are being handled by component, then please use multiple "describe" block
or else use single block

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.spec.ts
> +        title: 'Test Title',
Could you please use this mock data from a ts mock file rather than from spec file ?

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.ts
> +  public mapApiToCardData(apiData: ISavedSessions) {
No need for public -> functions are already public unless an access modifier specified

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.spec.ts
> +      code: 'Test Code',
Could you please move this mock data to a file and use it here

2023-04-11 08:55 UTC, sada-ajith commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/stack-card/stack-card.component.html
> +    <div *ngFor="let data of experienceDetails | keyvalue : returnZero">
do we need this compare function "returnZero"
I think it will work without comparator function
https://angular.io/api/common/KeyValuePipe

2023-04-11 08:57 UTC, sada-ajith commented
Please create shorter PRs if the issues are not time sensitive. I can see around 39 files , which relates to 3 different ticket
If one ticket is bigger and other 2 are supportive items , I'm okay with that

2023-04-11 09:25 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.scss
> +    margin-bottom: 10px;
replaced margin-bottom: 10px; 
with 
grid-row-gap: 10px;
row-gap: 10px;
for browsers supporting as well as not supporting row-gap

2023-04-11 09:56 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.spec.ts
> +        title: 'Test Title',
done

2023-04-11 10:55 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/saved-sessions/saved-sessions.component.spec.ts
> +  describe('viewLargeCard', () => {
changed to a single describe block.

2023-04-11 11:05 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/stack-card/stack-card.component.html
> +    <div *ngFor="let data of experienceDetails | keyvalue : returnZero">
need it to make sure the function does not sort the fields.

2023-04-11 11:22 UTC, grace-sadaindia commented on microservices/turbine-admin/apps/toboggan-app/src/app/prior-experiences/components/small-card/small-card.component.spec.ts
> +      code: 'Test Code',
test data moved to a separate mock file in services folder.

2023-04-12 09:35 UTC, sada-ajith approved these changes

2023-04-12 10:38 UTC, merged