assessment remove nestjs parts and directly call gpcore
snhuproduct/turbine pull request #442
Opened 2023-04-17 12:36 UTC by pran-sada

### Description

- Remove all assessment nestjs side except for learnosity

#### Video

[Turbine-Admin.webm](https://user-images.githubusercontent.com/116863369/232485783-0a16018c-00d7-47f2-b6e0-4dec1c1b48c3.webm)

### Other Details

- [SNHUT-5225](https://collectiveshift.atlassian.net/jira/software/c/projects/SNHUT/issues/SNHUT-5225)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2023-04-17 21:19 UTC, mk-sada approved these changes
Good work!

2023-04-17 21:19 UTC, mk-sada commented on microservices/turbine-admin/apps/toboggan-app/src/app/assessment/services/assessment.service.spec.ts
> +    const req = httpMock.expectOne(environment.GPCoreBaseUrl + `/assessment-service/api/v1/submitted-assessments?status=${SubmittedAssessmentFilterStatus.EvaluationPending}&skip=0&limit=100`,
Not a change request necessarily, just a suggestion: if you're already using backticks, might as well go all the way with it instead of using string concatenation alongside interpolation. E.g.:

```TypeScript
const req = httpMock.expectOne(`${environment.GPCoreBaseUrl}/assessment-service/api/v1/submitted-assessments?status=${SubmittedAssessmentFilterStatus.EvaluationPending}&skip=0&limit=100`,
```

2023-04-17 21:24 UTC, mk-sada requested changes
hrm, [unit-tests are failing](https://github.com/snhuproduct/turbine/actions/runs/4725877001/jobs/8384815710?pr=442#step:8:88) with error similar to following:

```
FAIL src/app/assessment/services/assessment.service.spec.ts
  ● AssessmentService › should have called api for getAssessmentByUuid

    Expected one matching request for criteria "Match URL: /api/assessments/assessment/1", found none. Requests received are: GET https://api.dev.leveluplabs.org/assessment-service/api/v1/assessment/1.

      87 |   it('should have called api for getAssessmentByUuid', () => {
      88 |     service.getAssessmentByUuid('1').subscribe();
    > 89 |     const req = httpMock.expectOne('/api/assessments/assessment/1');
         |                          ^
      90 |     expect(req.request.method).toBe('GET');
      91 |     req.flush([]);
      92 |   });
```

I suspect some test related cleanup is still due. 

Good work otherwise!

2023-04-18 06:13 UTC, pran-sada commented
Unit tests were failing after merging main into the branch. fixed those

2023-04-18 09:42 UTC, sada-ajith approved these changes

2023-04-18 09:51 UTC, merged